### ISSUE TITLE
Helping out with maintenance

### ISSUE THREAD

**Issue by blueyed** [pdbpp/pdbpp#100]
@antocuni 
I have several PRs open since a while, and there have been no new commits since October 2017.

I would like to ask if helping out with maintaining would be appreciated, and/or if you plan to do some maintenance yourself in the near future again.

Thanks!

**Comment by blueyed** [comment]
I am going to maintain a fork at https://github.com/blueyed/pdbpp/.

**Comment by antocuni** [comment]
Hi, I am embarrassed to have waited so long to answer: It is obvious that I cannot find enough time to maintain pdbpp, so your help is very appreciated.
I have invited you as a collaborator.

As a general guideline for maintenance: I am glad to improve pdbpp, but I would like to keep test coverage high. So in general, I have the same rule for PyPy: for every bug fix, there should be a new test which fails without (except very particular cases in which writing a test is impossible/excessively hard)

**Comment by blueyed** [comment]
@antocuni 
Thanks!

Would you be OK with a big PR from the fork, or should I create/update the existing ones?
Updating them would make sense, since some things needed followups later, so I will go with that then anyway I think.

Re test coverage: given that coverage.py and using sys.settrace do not work together there is not really a way to measure this, is there?  But at least maybe the tests could be covered?!
Is that maybe less a problem with pypy?

**Comment by antocuni** [comment]
>Re test coverage: given that coverage.py and using sys.settrace do not work together there is not really a way to measure this, is there? But at least maybe the tests could be covered?!

When I speak about "code coverage" I mean that every feature should have a test, even if we don't have an automated tool which spits out a percentage number :)
