### ISSUE TITLE
Don't override pdb by default

### ISSUE THREAD

**Issue by cirosantilli** [pdbpp/pdbpp#111]
That scares the H out of me and makes me not want to use this repo at first look.

If your software is good, I bet that you are losing lots of potential users because of that.

Also it did not work for me out of the box with:

     python3 -m pip install --user pdbpp

on Ubuntu 18.04, the following still uses the old PDB:

    pdb3 a.py

All best, Python really needs a decent CLI debugger urgently! Great initiative.

**Comment by blueyed** [comment]
Well, it is one of the main benefits: use it by default when installed.
You can still use `pdb.pdb.set_trace()` for the original one.

What is `pdb3`?  (from which package?  Something Ubuntu ships with Python, or something standalone?)

**Comment by cirosantilli** [comment]
It is provided by the Ubuntu package `python3-pip: /usr/bin/pip3` and seems to contain the same things as `Lib/pdb.py` from the main cython tree, and seems to be the main way to call ipdb from the CLI.

Same behaviour for `pdb` executable for Python 2.

**Comment by blueyed** [comment]
Still not sure what `pdb3` is (you mention python3-pip, but then `pip3`?!)

Anyway, closing the issue, because this is expected behavior.
