### ISSUE TITLE
pdbpp breaks curtsies

### ISSUE THREAD

**Issue by gpruss** [pdbpp/pdbpp#114]
Dear pdb++ developers,
I only recently upgraded to python 3.7 and discovered that one of my projects stopped working. I tried to figure out what's going on and set up a couple of virtual environments. When I simultaneously install bpython and pdb++, bpython crashes with the following traceback:

 Traceback (most recent call last):
  File "[...]/venv/bin/bpython", line 7, in <module>
    from bpython.curtsies import main
  File "[...]/venv/lib/python3.7/site-packages/bpython/curtsies.py", line 11, in <module>
    import curtsies
  File "[...]/venv/lib/python3.7/site-packages/curtsies/__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "[...]/venv/lib/python3.7/site-packages/curtsies/window.py", line 13, in <module>
    from .formatstring import fmtstr
  File "[...]/venv/lib/python3.7/site-packages/curtsies/formatstring.py", line 3, in <module>
    from typing import Iterator, Text, Tuple, List, Union, Optional
  File "[...]/venv/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "[...]/venv/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'

Same thing happens when I try to import curtsies in IDLE. As soon as I uninstall pdb++ everything works, again. Can anyone confirm that behavior?

Cheers,
Gunnar

**Comment by blueyed** [comment]
Please try the version from master.

I cannot see where/how pdb/pdbpp would be involved from the traceback above, but maybe it is related to other deps being used?!

**Comment by gpruss** [comment]
Hi blueyed,
thanks a lot for the suggestion - installing from master solves the issue :-)

I have absolutely no idea, how pdb++ and the error could be related. I installed (solely) bpython into an empty virtual machine for testing and it worked. Installing pdb++ on top of it made bpython crash with the above printed traceback pointing to curtsies. When I removed pdb++ (without touching it's deps, i.e. fancycompleter and wmctrl) it worked again. So the only difference between curtsies throwing an exception or not has been pdb++... 

Anyway, thank you very much for helping me out!

**Comment by blueyed** [comment]
Great.
Can you please try git-bisect to find which commit might have fixed it then?

**Comment by gpruss** [comment]
The bug has apparently been fixed by commit 50da69cf1a0aed2a838bbedb49da5bee21be026b

**Comment by blueyed** [comment]
Great, thanks for looking it up!

Closing this issue - hopefully there will be a release soon.
