### ISSUE TITLE
print and log statements in sticky mode

### ISSUE THREAD

**Issue by petobens** [pdbpp/pdbpp#122]
Hi! Consider the following simple file:
```python
import logging

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler()],
)

breakpoint()
x = 2
print(x)
y = 3
logger.info(y)
z = x + y
```
If I use `sticky_by_default = True` in my config file then when using `n` to move along lines both print and logger statements are ignored (not actually ignored but since the screen is repainted the message is lost/not shown). Is there a way to avoid using this while on sticky mode?

**Comment by blueyed** [comment]
Reminded me of https://github.com/antocuni/pdb/pull/79. /cc @callmekohei 

I usually disable sticky mode in this case (aliased to `st`).

I could imagine that first clearing the screen before continueing might help, i.e. in this case you would see the print output on top of the screen, although it might actually be better to see it below the code?!

**Comment by petobens** [comment]
Oh something like #79 looks great (and solves my problem). Pity the PR got closed.

**Comment by blueyed** [comment]
Yeah, would be cool to get this in pieces somehow (or re-vamped).

This should also do it (and handle #83 in another way):

```diff
 pdb.py | 17 +++++++++++------
 1 file changed, 11 insertions(+), 6 deletions(-)

diff --git i/pdb.py w/pdb.py
index 90c24df..0dc467e 100644
--- i/pdb.py
+++ w/pdb.py
@@ -746,10 +746,6 @@ def do_undisplay(self, arg):
 
     def _print_if_sticky(self):
         if self.sticky:
-            if self.first_time_sticky:
-                self.first_time_sticky = False
-            else:
-                self.stdout.write(CLEARSCREEN)
             frame, lineno = self.stack[self.curindex]
             filename = self.canonic(frame.f_code.co_filename)
             s = '> %s(%r)' % (filename, lineno)
@@ -793,8 +789,8 @@ def do_sticky(self, arg):
         """
         sticky [start end]
 
-        Toggle sticky mode. When in sticky mode, it clear the screen
-        and longlist the current functions, making the source
+        Toggle sticky mode. When in sticky mode, it clears the screen
+        and longlists the current functions, making the source
         appearing always in the same position. Useful to follow the
         flow control of a function when doing step-by-step execution.
 
@@ -853,6 +849,15 @@ def preloop(self):
                 print('%s: %r --> %r' % (expr, oldvalue, newvalue),
                       file=self.stdout)
 
+    def postloop(self):
+        super(Pdb, self).postloop()
+        if self.sticky:
+            if self.first_time_sticky:
+                self.first_time_sticky = False
+            else:
+                self.stdout.write(CLEARSCREEN)
+
+
     def _get_position_of_arg(self, arg):
         try:
             obj = self._getval(arg)
```

I'll improve it a bit (e.g. first_time_sticky should only be considered when coming from config / ignored when using `sticky` manually).

**Comment by blueyed** [comment]
Check out https://github.com/antocuni/pdb/pull/123.

You need to `pip install` without `-e`.

**Comment by blueyed** [comment]
@petobens check out https://github.com/pdbpp/pdbpp/pull/368 :)

**Comment by petobens** [comment]
Thank you! Will do.

**Comment by petobens** [comment]
Hey @blueyed I installed master branch with `pip3 install --user git+https://github.com/pdbpp/pdbpp` and now my config is not being read.. i.e I have `.pdbrc.py` in my home dir but the master branch doesn't seem to recognize it. On the other hand if i install the version on `pypi`  (version 0.10.2 by means of `pip3 install --user pdbpp`) then the config is correctly parsed. Any ideas of what might be going on? Thanks

For the record my config is: https://github.com/petobens/dotfiles/blob/master/python/pdbrc.py

**Comment by blueyed** [comment]
@petobens 
Have you tried adding some `print` there to check if it really not being read?
Otherwise try looking from the code in pdbpp.py where it gets read, and/or try to simplify it.
Let me know your findings.

**Comment by blueyed** [comment]
btw: I've thought to enable sticky by default, really enjoying it with the fixes/improvements.
I've also started experimenting with using an/the alternate screen for it (so that it does not end up page-by-page in the terminal's history/scrollback).

**Comment by petobens** [comment]
My bad... It was indeed reading the config I had to redefine my colors as 
```
    pygments_formatter_class = "pygments.formatters.TerminalTrueColorFormatter"
    pygments_formatter_kwargs = {"style": OneDarkish}
```
The improved sticky mode is beautiful.  Thank you!!!

**Comment by petobens** [comment]
I do have one related question (I can open a new issue for it though). Have you tried installing the master branch with poetry?. Given the following `pyproject.toml` file:
```toml
[tool.poetry]
name = "pbpp-poetry"
version = "0.1.0"
description = ""
authors = ["petobens <foo@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pdbpp = {git = "https://github.com/pdbpp/pdbpp"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
If I run `poetry install` this will indeed install the pdbpp master branch but if I run `poetry run python foo.py` on the following `foo.py` file:
```python
x = 2
breakpoint()
print(x)
y = 3
``` 
 then pdbpp is not activated (it falls back to the standard pdb). I guess this is because poetry installs the  gitpackage in development or "src" mode since `poetry run pip list` shows:
```
Package        Version                Location
-------------- ---------------------- -------------------------------------------------------------------------------------
fancycompleter 0.9.2.dev2-g8ae963e    /home/pedro/.cache/pypoetry/virtualenvs/pbpp-poetry-uIeetswW-py3.8/src/fancycompleter
pdbpp          0.10.3.dev170+g5eefc46 /home/pedro/.cache/pypoetry/virtualenvs/pbpp-poetry-uIeetswW-py3.8/src/pdbpp/src
pip            19.2.3
Pygments       2.6.1
pyrepl         0.8.5.dev44            /home/pedro/.cache/pypoetry/virtualenvs/pbpp-poetry-uIeetswW-py3.8/src/pyrepl
setuptools     41.2.0
six            1.14.0
wmctrl         0.3
```
On the other hand if I uninstall pdbpp git with `poetry remove pdbpp` and install the pypi version with `poetry add pbpp` then pdbpp works just fine since it is installed as a "library":
```

-------------- ------- ----------------------------------------------------------------------------------------------
fancycompleter 0.9.1   /home/pedro/.cache/pypoetry/virtualenvs/pbpp-poetry-uIeetswW-py3.8/lib/python3.8/site-packages
pdbpp          0.10.2  /home/pedro/.cache/pypoetry/virtualenvs/pbpp-poetry-uIeetswW-py3.8/lib/python3.8/site-packages
pip            19.2.3
Pygments       2.6.1
pyrepl         0.9.0   /home/pedro/.cache/pypoetry/virtualenvs/pbpp-poetry-uIeetswW-py3.8/lib/python3.8/site-packages
setuptools     41.2.0
wmctrl         0.3
```
Any pointers are greatly appreciated (I've also asked this on the poetry repo since I don't know whether this is a poetry or pdbpp issue/feature).

**Comment by petobens** [comment]
> (I've played around a bit with doing this also for develop-mode/editable installs, but it is not trivial, since pip does not support uninstalling extra files then.)

Hi @blueyed ! Given your answer above: there is no way for you to cut an intermediate release in the meantime? (I know we spoke about this before and you wanted to wait as per https://github.com/pdbpp/pdbpp/issues/260 but it's been 5months since the latest release (0.10.2)). If that's not possible is there any hack/workaround to install pdbpp in editable mode? Thanks!

**Comment by blueyed** [comment]
@petobens 
You can symlink the `.pth` file into your site-packages directory for example.
Also I tend to just `pip install ~/src/pdbpp` into my venvs anyway - I do not see why you have to go through poetry etc.

**Comment by petobens** [comment]
Ok. Thanks
