### ISSUE TITLE
Add aliases as in pdbrc

### ISSUE THREAD

**Issue by petobens** [pdbpp/pdbpp#124]
Is it possible to define aliases in the config file? In my previous `pbdrc` file I had things like:
```
# Print local variables
 alias pl print({k: v for k,v in locals().items() if '__' not in k and 'pdb' not in k})
```
Can a similar behaviour be achieved here? Thanks!

**Comment by blueyed** [comment]
`~/.pdbrc` is used by pdbpp also, i.e. the aliases should be in your pdb++ session also.

Please re-open if I am missing something.

**Comment by petobens** [comment]
Oh. Silly me. You're obviously right. Sorry for the noise.
