### ISSUE TITLE
"python -m pdb …" is broken

### ISSUE THREAD

**Issue by uweschmitt** [pdbpp/pdbpp#131]
In case I run `python -m pdb ...` I see the old `pdb` prompt not `(pdb++)`.

I guess this is related to the recent changes in Python 3.7 to offer a builtin `breakpoint` function. If I use `breakpoint()` instead of `import pdb; pdb.set_trace()` the `(pdb++)` appears.

**Comment by blueyed** [comment]
I cannot reproduce this myself with `pdb.set_trace()`, but noticed that `-m pdb` is buggy indeed (also with py27 though).

**Comment by uweschmitt** [comment]
Tried meanwhile  to reproduce my issue with `import pdb; pdb.set_trace()` in another virtual environment and now it works.  Still would be very nice if the `-m pdb` would work.

Btw: Thanks for `pdbpp` ! Made my life much easier.

**Comment by blueyed** [comment]
It was broken with https://github.com/antocuni/pdb/pull/108.

https://github.com/antocuni/pdb/pull/135/commits/d770b801023d79c34b5755c956e0ef12704984c9 appears to fix it as a stopgap solution.

**Comment by blueyed** [comment]
I've released 0.9.5 with this fix now: https://pypi.org/project/pdbpp/
