### ISSUE TITLE
`AttributeError: 'NoneType'` with `python -m pdb`

### ISSUE THREAD

**Issue by bhrutledge** [pdbpp/pdbpp#132]
Hi there! First, thanks for this. I was reminded of it from Clayton Parker's [So you think you can PDB?](https://www.youtube.com/watch?v=P0pIW5tJrRM) talk at PyCon 2015.

I've got a particular use case where it would be easier to run `python -m pdb` and set a breakpoint, rather than using `pdb.set_trace()`. However, when I try that, I get the following exception:

```
$ python -m pdb test.py
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/brian/Code/test-pdbpp/venv/lib/python2.7/site-packages/_pdbpp_path_hack/pdb.py", line 5, in <module>
    exec(compile(f.read(), pdb_path, 'exec'))
  File "/Users/brian/Code/test-pdbpp/venv/lib/python2.7/site-packages/pdb.py", line 1165, in <module>
    pdb.main()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1329, in main
    traceback.print_exc()
AttributeError: 'NoneType' object has no attribute 'print_exc'
```

Some more details:

```
$ python --version
Python 2.7.15

$ pip freeze
fancycompleter==0.8
pdbpp==0.9.3
Pygments==2.3.1
pyrepl==0.8.4
wmctrl==0.3

$ cat test.py
print('Hello World!')
```

If I uninstall pdbpp, I get the expected result:

```
$ python -m pdb test.py
> /Users/brian/Code/test-pdbpp/test.py(1)<module>()
-> print('Hello World!')
(Pdb)
```

**Comment by blueyed** [comment]
Yeah.. this appears to be due to pdb resetting the globals - the original exception (with py27) is that `bdb` is None in `pdb.Pdb.reset` already.

**Comment by bhrutledge** [comment]
In Python 3, there's no exception, but it starts the built-in `pdb`:

```
$ python --version
Python 3.7.2

$ python -m pdb test.py
> /Users/brian/Code/test-pdbpp/test.py(1)<module>()
-> print('Hello World!')
(Pdb) 
```

Would it be possible to provide a different module entry point, so that something like `python -m pdbpp test.py` or `python -m pdp.run test.py` would work? Or maybe a dedicated command-line tool, like `pdbpp test.py`? [PuDB offers both of these](https://documen.tician.de/pudb/starting.html#getting-started), implemented via [`console_scripts`](https://github.com/inducer/pudb/blob/master/setup.py#L60).

**Comment by blueyed** [comment]
JFI: Working on a fix for `-m pdb` in #135.  The stopgap solution is to revert #108.

**Comment by blueyed** [comment]
https://github.com/antocuni/pdb/pull/135 was merged, so this should work again on master.
I plan to do a release soon, so please consider testing/verifying it.

As for `python -m pdbpp`: since it is meant to replace/hijack the `pdb` module itself, it should not be necessary.

But something like #134 makes sense, when you want to skip this, without uninstall pdbpp.

**Comment by blueyed** [comment]
I've released 0.9.5 with this fix now: https://pypi.org/project/pdbpp/

**Comment by tmzhuang** [comment]
How can we get a pdb++ prompt when using post-mortem debugging via "-m pdb"?

**Comment by blueyed** [comment]
@tmzhuang
> How can we get a pdb++ prompt when using post-mortem debugging via "-m pdb"?

Works for me.

Given `t-pm.py´:
```python
print(1)
assert False
print(2)
```

`python -m pdb -c cont t-pm.py`:
```
1
Traceback (most recent call last):
  File "/usr/lib64/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/usr/lib64/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/tmp/t-pm.py", line 1, in <module>
    print(1)
AssertionError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
[4] > /tmp/t-pm.py(1)<module>()
-> print(1)
(Pdb++) q
Post mortem debugger finished. The t-pm.py will be restarted
[2] > /tmp/t-pm.py(1)<module>()
-> print(1)
(Pdb++) q
```

**Comment by tmzhuang** [comment]
Hmm. 
`pip show sbtest`:

> Name: sbtest
Version: 0.1
Summary: Package for driving automated testing.
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/tzhuang/proj/grunt/branches/storyboard_sandbox/infrastructure/packages/sbtest
Requires: django, django-extensions, django-debug-toolbar, ssh2-python, psycopg2-binary, mysqlclient, tabulate, pypugjs, inflection
Required-by: 

`python -V`:

> Python 3.7.3

`pip show pdbpp`:

> Name: pdbpp
Version: 0.9.3
Summary: pdb++, a drop-in replacement for pdb
Home-page: http://github.com/antocuni/pdb
Author: Antonio Cuni
Author-email: anto.cuni@gmail.com
License: BSD
Location: /home/tzhuang/.pyenv/versions/3.7.3/envs/sandbox/lib/python3.7/site-packages
Requires: fancycompleter, wmctrl, pygments
Required-by: 

`python -m pdb -m sbtest`

> > /home/tzhuang/proj/grunt/branches/storyboard_sandbox/infrastructure/packages/sbtest/sbtest/__main__.py(1)<module>()
-> if __name__ == '__main__':
(Pdb)

**Comment by blueyed** [comment]
> Version: 0.9.3

That is very old.
The latest release should have the fix.
(but I even recommend using master currently (there are many fixes/improvements there since the last release) - if you know how to install/handle that, otherwise just update to the last release)

**Comment by blueyed** [comment]
Also I am not sure what you expect it to do really - it also appears to work as-is.
But I do not know what `sbtest` is (supposed to do).

**Comment by tmzhuang** [comment]
Hey Daniel,

Thanks for the quick responses. What module sbtest is doesn't really
matter; I was just trying to illustrate that I wasn't able to get a
post-mortem pdb++ prompt. I will update to a newer version of pdbpp and let
you know how it goes. Thanks for your help!

**Comment by blueyed** [comment]
@tmzhuang 
You are getting the prompt already.
A post-mortem would only happen in case of an error.
So if there is one, you should use `python -m pdb -c cont -m sbtest` probably (or just use `c` with the initial prompt).

When testing this behavior try also `PDBPP_HIJACK_PDB=0 python -m pdb …` to use the original pdb (certainly requires the latest release).
