### ISSUE TITLE
Possible bug: can't interact with pdbpp prompt

### ISSUE THREAD

**Issue by McEileen** [pdbpp/pdbpp#187]
Hi, I'm attempting to use pdbpp to debug a dockerized python-flask application.  I was able to access the pdbpp prompt by setting a breakpoint with `pdbpp.set_trace()` and running this command in terminal: 
`docker-compose run --rm -p 3000:3000 myApp flask run --host=0.0.0.0 --port=3000`  
When I attempt to type a command in the pdbb prompt, it fails to process the command.  See below for an example: 
```bash
[34] > MyApp/app/main/forms.py(35)FindUserForm()
-> name = StringField(
(Pdb++) list
*** NameError: name 'lt' is not defined
(Pdb++) l
*** NameError: name 'lt' is not defined
(Pdb++) list
```

I'm using a virtualenv with Python 3.7.1, pdbpp 0.9.15 and Docker version 18.09.03.  My OS is Ubuntu 18.0.4.

I had a similar error when using `ipdb` and had switched to `pdbpp` after reading [this stackoverflow thread](https://stackoverflow.com/questions/40834092/cant-type-in-ipdb-console-in-docker-container).  

I tried adding the below lines to the `myApp` service in my `docker-compose.yml` file 
```bash
     stdin_open: true
        tty: true
```
Unfortunately, it didn't resolve the issue.  Have other users seen this error when debugging with pdbpp?

**Comment by blueyed** [comment]
> by setting a breakpoint with `pdbpp.set_trace()`

That would be `pdb.set_trace()`, right?

Try using `-it` with docker-run to pass stdin.

From the example above it looks like only some of it is arriving/handled, e.g. "list" becomes "lt".

**Comment by blueyed** [comment]
Ah, this is docker-compose.  Try directly with docker maybe.
I've not tried to reproduce it myself yet, but should be easy I guess.

**Comment by McEileen** [comment]
Correct, it was `pdb.set_trace()`.  Thanks for the correction.
I removed the below lines from the `docker-compose.yml`
```bash
stdin_open: true
tty: true
```
Then I switched to `pdb` instead of `pdbpp` and I can now successfully debug the app.  However, I switched back to `pdbpp` and saw the same issue on my second interaction with the debugger prompt.
```bash
[34] > /usr/src/app/MyApp/app/main/forms.py(35)FindUserForm()
-> name = StringField(
(Pdb++) list
[34] > /usr/src/app/MyApp/app/main/forms.py(36)FindUserForm()
-> 'name', default='', validators=[Regexp('\w*'), Length(max=50),
(Pdb++) continue
*** NameError: name 'litcnnecniu' is not defined
```
Thanks for the help, @blueyed.  I am going to stop debugging this and switch to using pdb instead of pdbpp.  I'll leave the issue open in case anyone wants to investigate this behavior, but I also understand if the repo owner closes the issue.

**Comment by blueyed** [comment]
Does it also happen with pdb++ installed and using `pdb.pdb.set_trace()` (this goes through to the original pdb then)?

It really looks like two processes are fighting over stdin there.. "litcnnecniu" is just parts of the words from your commands (and the other used the Enter probably).

**Comment by McEileen** [comment]
Yes, I get the same error when I have pdb++ installed and use `pdb.pdb.set_trace()`.

You are correct that two processes were fighting over stdin.  After debugging with some other folks, I learned that the bug occurs when the breakpoint is placed in a class, such as `FindUserForm()` in `forms.py`, but not when the breakpoint is in a view, like the view for the `/find` route in `views.py`.  (Context: When I was able to successfully debug with pdb, I happened to be placing a breakpoint in a view.)  

Unlike views, the class is loaded at import time, which starts a pdb process.  Then, a second pdb process is triggered by the werkzeug reloader.  Since these two processes are competing over the stdin, neither can properly process the input.  

You can get around the bug by setting `FLASK_DEBUG: 0`, as that disables the werkzeug reloading.

**Comment by blueyed** [comment]
Great, thanks for following up!

Are both pdb processes pdb++ then, or does werkzeug reloader use the real pdb (or its own maybe even)?
(asking since pdb++ has some sort of support for a global Pdb instance already, which might come in handy here to detect this situation)

Just for postery, I've tried it with a simple Dockerfile before (might help others in the future for debugging):
```Dockerfile
FROM python:alpine

RUN pip install pdbpp

RUN echo "import pdb, textwrap; pdb.set_trace()" >> t.py
RUN echo "print(textwrap.indent('foo', '    '))" >> t.py

ENTRYPOINT ["python", "t.py"]
```

**Comment by blueyed** [comment]
Closing, feel free to followup still of course.

**Comment by McEileen** [comment]
> Are both pdb processes pdb++ then, or does werkzeug reloader use the real pdb (or its own maybe even)?

When I had pdb++ installed and interacted with the debugger prompt, it appeared to be pdb++, as seen below.
```bash
[34] > /usr/src/app/MyApp/app/main/forms.py(35)FindUserForm()
-> name = StringField(
(Pdb++) 
```
  This makes me think that both processes were pdb++.  If you want me do further investigation to confirm this, please let me know what steps you consider necessary.

**Comment by blueyed** [comment]
I could imagine the second instance might not be displaying its/any output, i.e. stdout is connected to a single instance only.
Anyway, I am glad you got it figured out.  Thanks for the report and details you've provided!

**Comment by blueyed** [comment]
I've noticed a similar issue with django-extensions / django-pdb: you basically should disable threading in the server when using pdb (https://github.com/django-extensions/django-extensions/pull/1360).

**Comment by blueyed** [comment]
Coming back to this once more: the GLOBAL_PDB is the issue after all.. it should not be shared across threads in the first place.
https://github.com/antocuni/pdb/pull/202 should fix this.
