### ISSUE TITLE
post_mortem does not reenable py.test stdio capture

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#19]
Originally reported by: **Ronny Pfannschmidt (Bitbucket: [RonnyPfannschmidt](https://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](https://github.com/RonnyPfannschmidt))**

----------------------------------------

its a evil neat trick to abuse post_mortem in loops and jsut keep going

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/19

**Comment by blueyed** [comment]
I think this addressed in pytest with https://github.com/pytest-dev/pytest/pull/2619.

Please re-open if I misunderstood it, which is likely since you posted it here instead as for pytest.
