### ISSUE TITLE
realgud:pdb-remote can't track the file location with pdbpp

### ISSUE THREAD

**Issue by TauPan** [pdbpp/pdbpp#208]
At least it's not obvious how to achieve that. When I install pdbpp instead of pdb, file tracking in realgud:pdb-remote in emacs stops working and it starts working again when I uninstall pdbpp.

python 3.4.4
emacs 26.2
realgud.el: 1.4.5
pdbpp-0.10.0

Not sure what else might be relevant.

**Comment by blueyed** [comment]
For reference: https://github.com/realgud/realgud

pdbpp hijacks the `pdb` module, resulting in different results for realgud somewhere likely.

With https://github.com/antocuni/pdb/commit/38619469b6f79e42747215338744789b14774947 you/it can use `PDBPP_HIJACK_PDB=0` - let me know if that works and I might cut a new release.

Would be interesting to know however why/where it breaks.

Also it is not clear if it would not be beneficial to have pdbpp with realgud?

**Comment by blueyed** [comment]
You can also configure it to use `pdb.pdb` (where pdbpp stored the orig pdb) probably.
(https://github.com/realgud/realgud/wiki/pdb-notes)

**Comment by TauPan** [comment]
Thanks for the pointers. Indeed I think having pbdpp within realgud with full tracking would be the preferable. I'll try to find some time to investigate how tracking in realgud works later.

**Comment by TauPan** [comment]
With 3861946 PDBPP_HIJACK_PDB=0 works and gives me plain old pdb with source tracking, as if pbd++ was not installed. As an alternative I'm not sure how I would configure `realgud:pdb-command-name` to achieve the same effect. (Setting it to `python -m pdb.pdb` does not work, so I'd probably have to create a small script.

**Comment by TauPan** [comment]
I figured out what irritates realgud:pdb about pbd++'s source location lines: the leading '[2]', whatever that means. (Sorry, I didn't read the docs or anything.)

Edit: To clarify, my session looks like this:
```python
Current directory: /home/friedel/git/roskilde-program-spider/tests/
Command: python -m pdb /home/friedel/git/roskilde-program-spider/tests/test_main.py
[2] > /home/friedel/git/roskilde-program-spider/tests/test_main.py(1)<module>()
-> import datetime
(Pdb++) n
[2] > /home/friedel/git/roskilde-program-spider/tests/test_main.py(2)<module>()
-> import json
(Pdb++) 
```

When I eval the following emacs lisp, realgud:pdb tracks source lines with pdb++ for me:
```elisp
(setf (gethash "loc" realgud:pdb-pat-hash)
      (make-realgud-loc-pat
       :regexp "> \\(\\(?:[a-zA-Z]:\\)?[-a-zA-Z0-9_/.\\\\ ]+\\)(\\([0-9]+\\))"
       :file-group 1
       :line-group 2))
```

(The original regexp starts with '^', expecting the '>' at the beginning of the line.)

See here: https://github.com/realgud/realgud/blob/master/realgud/debugger/pdb/init.el#L49

Not sure how to proceed. It doesn't really look like pdb++ is broken in any way and the adaptation needed for realgud:pdb to work is very tiny.

**Comment by blueyed** [comment]
Thanks for the info.  The leading `[2]` is the tb/frame index.

**Comment by blueyed** [comment]
With regard to improved threading support I've experimented with adding the name of non-main threads into the prompt (but after the `(Pdb++)`) - maybe the frame could be displayed also in that line.
Or it could be moved to the end of the line where it's now.

But in general it probably good to relax the regexp used by realgud a bit in this regard.

**Comment by TauPan** [comment]
See https://github.com/realgud/realgud/issues/245 in which @rocky explains that he would prefer that I create a seperate repository for pdb++ support in realgud. I'll see what I can do, since I'm probably the only one who wants that feature right now.

Edit: I think unless **you** specifically want pdb++ to be supported in realgud in emacs, we can close this issue as well.

**Comment by blueyed** [comment]
Ok, closing then for now.

**Comment by TauPan** [comment]
To give an update, I've created a personal workaround for this use-case of mine, see https://github.com/realgud/realgud/issues/245#issuecomment-489362213 and updated the issue description https://github.com/realgud/realgud/issues/245 to reflect that.

**Comment by TauPan** [comment]
Another update: My personal workaround doesn't work for some reason (see https://github.com/realgud/realgud/issues/245). I'm afraid I have to disable pdb++ for now, as source file tracking is more important for me than other features it offers.

**Comment by rocky** [comment]
There is now a realgud pdb++ add-on. See  https://github.com/realgud/realgud-pdbpp
