### ISSUE TITLE
How do you configure things you want initialized?

### ISSUE THREAD

**Issue by fbicknel** [pdbpp/pdbpp#237]
Say you wanted to always do something like this when you start the debugger and have it in your namespace:

`from pprint import pprint as pp`

How would you do that in the `.pdbrc.py`? or... someplace else?

**Comment by blueyed** [comment]
`~/.pdbrc` works for this with both pdb++ and pdb - I have e.g. `import os, sys` there.
I am using `~/.pdbrc.py` for a custom `Config`, and to setup readline/pyrepl history.

As for `pp`: it should be there by default already, no?
https://github.com/xdegaye/cpython/blob/dd9f66485d6bf8893ae0b02ff4d622ec343236c7/Lib/pdb.py#L1184

**Comment by fbicknel** [comment]
Ah, thanks. Didn't consider .pdbrc

And you're right... pp was a poor example. 😁

**Comment by fbicknel** [comment]
I knew I remembered this differently. This is why:

(Pdb++) pp bar.__dict__
{'_state': <django.db.models.base.ModelState object at 0x7fc43658b710>,
'approver': u'fidgit', 'id': 8649, 'is_sox': False, 'name': u'host3',
'realm_id': 6886, 'status': u'A'}
(Pdb++) from pprint import pprint as ppp
(Pdb++) ppp(bar.__dict__)
{'_state': <django.db.models.base.ModelState object at 0x7fc43658b710>,
 'approver': u'fidgit',
 'id': 8649,
 'is_sox': False,
 'name': u'host3',
 'realm_id': 6886,
 'status': u'A'}
(Pdb++)

Again... this is just noise. I thought it was interesting, though.

<https://about.me/fbicknel?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Frank Bicknell
about.me/fbicknel
<https://about.me/fbicknel?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by blueyed** [comment]
The difference is due to pdbb setting/using `width` according to your terminal width, i.e. with something shorter (`{'foo': 'bar', 2: 3}`) it will look the same.

https://github.com/antocuni/pdb/blob/6e9bf1e36d6cfdf74f3850473542383d60423f5c/pdb.py#L893-L898

(just noticed this when looking into it swallowing exceptions from `__repr__`)

**Comment by blueyed** [comment]
Closing as answered.
