### ISSUE TITLE
Enable command completion (say for "b")

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#26]
Originally reported by: **pengyu.ut (Bitbucket: [pengyuut](https://bitbucket.org/pengyuut), GitHub: Unknown)**

----------------------------------------

I'm wondering if there is a way to enable command completion. For example, if there is a python file in the current directory, I want to use tab to complete its file name. Thanks.

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/26

**Comment by blueyed** [comment]
By now the original pdb's completion is also used, which by default completes after `b´ - but for some reason pdb that does not really work in this case.

**Comment by blueyed** [comment]
It works when not using pyrepl.

**Comment by blueyed** [comment]
Note that this either requires you to not use pyrepl, or the fixed one from https://github.com/pdbpp/pyrepl.
