### ISSUE TITLE
`edit` command is opening extra files

### ISSUE THREAD

**Issue by antoine-gallix** [pdbpp/pdbpp#264]
followup to https://github.com/pdbpp/pdbpp/issues/94

When using the `edit` command, my editor (sublime text) does correctly opens the correct file and the correct line, but at the same time also opens two new files, `{filename}` and `+38`, 38 beeing the line that I wanted to edit.

My `.pdbrc.py` file:

```
import pdb

class Config(pdb.DefaultConfig):
    sticky_by_default = True
    editor = "subl {filename}:{lineno}"
```

**Comment by blueyed** [comment]
Are you using pdbpp master?  (IIRC this has not been released yet)

**Comment by antoine-gallix** [comment]
My bad, I recently reset my environment and the PyPI pdb++ came back instead of the latest master.
