### ISSUE TITLE
Color settings ignored

### ISSUE THREAD

**Issue by con-f-use** [pdbpp/pdbpp#280]
This is my `~/.pdbrc.py` file:

```
import pdb

class Config(pdb.DefaultConfig):
    pygments_formatter_class = "pygments.formatters.TerminalTrueColorFormatter"
    pygments_formatter_kwargs = {"style": "solarized-light"} # python -c 'from pygments.styles import get_all_styles; print(list(get_all_styles()))'
    use_pygments = True
    sticky_by_default = True
```

No matter what values I substitude for `solarized-light` or `pygments.formatters.TerminalTrueColorFormatter` or if I comment the formatter line completely, I always get the default theme with no changes. Pygments is installed, I have no error messages when starting pdb++ and these are my available styles:

```
python -c 'from pygments.styles import get_all_styles; print(list(get_all_styles()))'                               
['solarized-dark', 'monokai', 'manni', 'colorful', 'igor', 'lovelace', 'xcode', 'murphy', 'paraiso-dark', 'vim', 'autumn', 'stata-light', 'abap', 'bw', 'sas', 'stata-dark', 'rrt', 'pastie', 'rainbow_dash', 'native', 'solarized-light', 'paraiso-light', 'perldoc', 'borland', 'trac', 'arduino', 'default', 'tango', 'fruity', 'vs', 'emacs', 'algol_nu', 'stata', 'algol', 'friendly']
``` 

I know the rest of the config works, because pdb++ starts in sticky mode and is responsive to changes in this particular setting. It just ignores the pygments settings completely.

**Comment by blueyed** [comment]
Are you using Git master?

**Comment by con-f-use** [comment]
No, I'm using the version from pypi:
```
$ pip freeze | grep pdbpp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
pdbpp==0.10.0
```

**Comment by blueyed** [comment]
It was only merged recently - unfortunately reflected in the README.

Please try the Git master version - I recommend cloning it and then "pip install …" it (without `-e` / `--editable`).

There are many improvements in master - releasing it is currently blocked though, mainy because of deps. See https://github.com/pdbpp/pdbpp/issues/260.

**Comment by jnns** [comment]
For everyone experiencing this issue: it is still present in `0.10.2` and blueyed's suggestion to use the current `master` still applies.

**Comment by jessedhillon** [comment]
I am still experiencing this in `0.10.3` using the exact config mentioned in the `README` (or the one in this thread) and Pygments `2.13.0`

---
I was able to resolve this by using the following `.pdbrc.py`:

```python
try:
    import pdb
    import pygments.formatters


    class Config(pdb.DefaultConfig):
        formatter = pygments.formatters.TerminalTrueColorFormatter(
            style='solarized-dark',
        )
        use_pygments = True
except ModuleNotFoundError:  # in case pygments is not installed
    pass

```
