### ISSUE TITLE
How to set a breakpoint?

### ISSUE THREAD

**Issue by asdf8601** [pdbpp/pdbpp#281]
Hi guys, 

I'm starting to use `pdb++` and I found a little confusing the Usage section, I would like to know how to set a breakpoint using `pdb++`. In the `README` file, it tells us that if I use `import pdb; pdb.set_trace()` I will be using the old `pdb`. However in the below examples it uses the same statement to start the debugger, so, whats is the equivalent `import pdb; pdb.set_trace()`  to set a breakpoint with `pdb++`?

**Comment by blueyed** [comment]
The README says:

> The old pdb module is still available by doing e.g. import pdb; pdb.pdb.set_trace().

Note the "pdb.pdb" there.
"pdb.set_trace()" should use the new / hijacked method.

**Comment by asdf8601** [comment]
Oh, I see it! thank you for the appointment, and sorry for the noise.
