### ISSUE TITLE
black?

### ISSUE THREAD

**Issue by davidszotten** [pdbpp/pdbpp#287]
would you accept a patch running black on the codebase and adding it as a lint step (possibly adjusting flake8 config if required)?

**Comment by blueyed** [comment]
I'm -0 on this.
I have quite a lot of stashes/local branches where this would create unnecessary conflicts.

It is good for new code however.

**Comment by davidszotten** [comment]
ok.

> It is good for new code however.
does black have a mode that formats parts of files only?

**Comment by blueyed** [comment]
> does black have a mode that formats parts of files only?

No.  (https://github.com/psf/black/issues/245)

[pre-commit](https://github.com/pre-commit/pre-commit) could be used to check only changed files/hunks.  This would require to add config for it and install it manually.
And it does not work on CI, where it can only be run selectively per file apparently (https://pre-commit.com/#usage-in-continuous-integration).

Not really worth it currently I think - but we can revisit integration of black later.
