### ISSUE TITLE
Improve frame command to move between frames

### ISSUE THREAD

**Issue by petobens** [pdbpp/pdbpp#298]
Would it be possible to add a `frame` command that allows to jump between frames as in https://stackoverflow.com/a/37402920/2149400 ?

My main use case is during post mortem debugging where pdb opens at the oldest/original frame (the innermost exception) and I have to press `up` several times to reach the conflicting line in my code. More details in this so question: https://stackoverflow.com/a/37402920/2149400

**Comment by blueyed** [comment]
The SO page does not load, but there is `f(rame) [index]` already:
https://github.com/pdbpp/pdbpp/blob/a8104d32ac88e08daa22182f458481c7119d1921/pdb.py#L1359-L1363

**Comment by petobens** [comment]
Ohh I didn't see that (thanks for pointing it out).  I've noticed a couple of things (which maybe can be improved/fixed):
1. If I press `f` by itself I get `*** Expected a number, got ""` (I would expect it to show the current frame)
2. I know I can go the first frame with `f 0`: is there a way to go the last one? (if 1. would work and `current` means last one then running simply `f` would be enough; otherwise could be possible to run `f -1` to achieve such behaviour?)

Thanks!

**Comment by blueyed** [comment]
Good points.

For top/bottom I am using https://github.com/fschulze/pytest-pdb/blob/master/pytest_pdb.py#L97-L113 usually, but it makes sense to have it here already.

Feel free to try creating a PR for it, of course - otherwise I might come to it myself eventually.

**Comment by blueyed** [comment]
@petobens 
Also make sure to use master already - many improvements since the release.  Needs `pip install` in non-editable mode (i.e. no `-i`).

**Comment by petobens** [comment]
> Feel free to try creating a PR for it, of course - otherwise I might come to it myself eventually.

Yeah it would be a good addition here. Might give the PR a shot (no promises though)
