### ISSUE TITLE
Tab complete has stopped working

### ISSUE THREAD

**Issue by liavkoren** [pdbpp/pdbpp#350]
I've recently migrated to a new machine, and PDBpp in general seems to be working fine (I've enabled sticky mode, eg) except that hitting tab doesn't generate an autocompletion, it just moves the cursor over four spaces.

Versions:
pdbpp==0.10.2
Python 3.7.6
fancycompleter==0.8
OS X 10.14.6

Fancycompleter imports correctly into a python shell.

Pdbrc file is:
```
import pdb


class Config(pdb.DefaultConfig):
    sticky_by_default = True
```

**Comment by ymyke** [comment]
Were you able to solve this? I seem to be having the same issue. #411

**Comment by ymyke** [comment]
Running pytest with the `-s` option solved the issue for me.

**Comment by liavkoren** [comment]
@ymyke  I think it stopped at some point when I rebuilt my venv..
