### ISSUE TITLE
Environment variable PDBPP_COLORS not mentioned anywhere, remove code?

### ISSUE THREAD

**Issue by Maltimore** [pdbpp/pdbpp#374]
In the pdbpp.py code, there is an if-branch checkinf for PDBPP_COLORS in the environment variables:

```
        if "PDBPP_COLORS" in os.environ:
            use_colors = bool(int(os.environ["PDBPP_COLORS"]))
            self.config.highlight = self.config.use_pygments = use_colors
```

This isn't documented anywhere. Could it be removed?

**Comment by blueyed** [comment]
@Maltimore 
It's considered to be experimental - and only used in tests for now.
It's meant to force (non-)usage of colors.

Does it bother you?
(The plan is to eventually document it.)

**Comment by Maltimore** [comment]
I just stumbled across it while trying to debug a different issue I have (whatever pygments colorscheme I set in the config, it gets ignored). So then I wondered what the PDBPP_COLORS was all about and whether I was missing something. But if you plan to use it in the future, then this is clearly not a bug and I'll close this issue :)
