### ISSUE TITLE
Selecting a colorscheme with Pygments only works on recent commit(s), not with released version.

### ISSUE THREAD

**Issue by Maltimore** [pdbpp/pdbpp#377]
Selecting a colorscheme fails silently with pdbpp when installed with, for instance, conda. However, when installing from the most recent commit in the master branch of this repo, it works. Maybe time to cut a release? :)

**Comment by blueyed** [comment]
A release is blocked due to https://github.com/pdbpp/pdbpp/issues/260.
Part of a solution would be getting rid of the fancycompleter dependency / making it optional (also relevant for #376).
For the time being I recommend to install from / use the master branch.

**Comment by blueyed** [comment]
Closing this for now - it seems you've followed the README from GitHub, which is for the master branch, but used an older release.

**Comment by jnns** [comment]
I'm having difficulty setting up syntax highlighting with both the latest PyPi release as well with the current master branch. 

Maybe this issue can be re-opened so others can find out about this problem more easily? 

As for the problem itself: the current master version does not seem to apply any syntax highlighting whatsoever. With or without a config file present I only get output like this:

![grafik](https://user-images.githubusercontent.com/206281/150333375-b8a95030-5c52-4875-8e49-63e90b966a13.png)

This is what I used to install the current master branch:

<details>
  <summary><tt>pip install -e git+https://github.com/pdbpp/pdbpp.git#egg=pdbpp</tt></summary>

```
Obtaining pdbpp from git+https://github.com/pdbpp/pdbpp.git#egg=pdbpp
  Updating ./.venv/src/pdbpp clone
  Running command git fetch -q --tags
  Running command git reset --hard -q b757794857f98d53e3ebbe70879663d7d843a6c2
  Preparing metadata (setup.py) ... done
Collecting fancycompleter@ git+https://github.com/pdbpp/fancycompleter@master#egg=fancycompleter
  Cloning https://github.com/pdbpp/fancycompleter (to revision master) to /tmp/pip-install-inksw7qt/fancycompleter_05a44e3c8ae543d6a86dd82b3ec8e888
  Running command git clone --filter=blob:none -q https://github.com/pdbpp/fancycompleter /tmp/pip-install-inksw7qt/fancycompleter_05a44e3c8ae543d6a86dd82b3ec8e888
  Resolved https://github.com/pdbpp/fancycompleter to commit 8ae963eff76b327b7533f39f40d04eb2b99fa3fd
  Preparing metadata (setup.py) ... done
Requirement already satisfied: wmctrl in ./.venv/lib/python3.10/site-packages (from pdbpp) (0.4)
Requirement already satisfied: pygments in ./.venv/lib/python3.10/site-packages (from pdbpp) (2.11.2)
Requirement already satisfied: six in ./.venv/lib/python3.10/site-packages (from pdbpp) (1.16.0)
Collecting pyrepl@ git+https://github.com/pdbpp/pyrepl@master#egg=pyrepl
  Cloning https://github.com/pdbpp/pyrepl (to revision master) to /tmp/pip-install-inksw7qt/pyrepl_ae94bcbf7c674be490712cda320cba02
  Running command git clone --filter=blob:none -q https://github.com/pdbpp/pyrepl /tmp/pip-install-inksw7qt/pyrepl_ae94bcbf7c674be490712cda320cba02
  Resolved https://github.com/pdbpp/pyrepl to commit f1e5513e069c8b2fac5380fa7869277a6360b65a
  Preparing metadata (setup.py) ... done
Installing collected packages: pdbpp
  Attempting uninstall: pdbpp
    Found existing installation: pdbpp 0.10.4.dev217+gb757794
    Uninstalling pdbpp-0.10.4.dev217+gb757794:
      Successfully uninstalled pdbpp-0.10.4.dev217+gb757794
  Running setup.py develop for pdbpp
Successfully installed pdbpp-0.10.4.dev217+gb757794
```
</details>

Version 0.10.3 however seems to use syntax highlighting but I have no means of changing the theme to something more legible.

![grafik](https://user-images.githubusercontent.com/206281/150333624-545df2bf-4330-4f11-bc0f-ca1ee713104a.png)

This is the `~/.pdbrc.py` I used:

```python

import pdb


class Config(pdb.DefaultConfig):
    pygments_formatter_class = "pygments.formatters.TerminalTrueColorFormatter"
    pygments_formatter_kwargs = {"style": "solarized-dark", "bg": "dark"}
```

**Comment by jugmac00** [comment]
Have a look at my documentation PR: https://github.com/pdbpp/pdbpp/pull/440/files

If I recall correctly, you need to `import pdbpp`. Though, my PR is almost a year old, so I may not remember correctly.

**Comment by jnns** [comment]
Thanks @jugmac00 . As there's no `pdbpp` module anymore, `import pdbpp` doesn't seem to work. I tried with 0.10.3 and current master.
