### ISSUE TITLE
Possible to use without hijacking default pdb?

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#39]
Originally reported by: **reckoner (Bitbucket: [reckoner](https://bitbucket.org/reckoner), GitHub: [reckoner](https://github.com/reckoner))**

----------------------------------------

Hi,

I really love this debugger, but unfortunately because it interferes with some other code, I cannot have it hijack the default pdb. Is there a way to stop this particular feature and just use the debugger explicitly ( without implicit pdb hijacking).

Thanks!

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/39

**Comment by antocuni** [comment]
*Original comment by* **Ronny Pfannschmidt (Bitbucket: [RonnyPfannschmidt](https://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](https://github.com/RonnyPfannschmidt))**:

----------------------------------------

currently not

**Comment by blueyed** [comment]
You can use `pdb.pdb.set_trace()`, if that is enough?
