### ISSUE TITLE
Unable to enter sticky mode when the function is decorated with hydra

### ISSUE THREAD

**Issue by binshengliu** [pdbpp/pdbpp#391]
Hi, I encountered a problem when using pdbpp to debug a function decorated with [hydra](https://github.com/facebookresearch/hydra). It's a package that manages parameters/configurations. Entering the `sticky` mode triggers this error:

`** Error in inspect.getsourcelines: source code not available **`

I looked a bit into both packages and it seems pdbpp/inspect got confused with the changed `current working dir`. In its decorator hydra sets up a new working directory every time the program is run. When the debugger is triggered within the function, it can't locate the source file and triggered some error checks in the `inspect` module. It also seems related to some type checks in `inspect`. I also tried pure pdb and it doesn't have this problem of displaying code. I initially filed an [issue](https://github.com/facebookresearch/hydra/issues/513) to hydra but it seems more relevant here.

I've found two workarounds so far.

1. Call the source file using an absolute path.
   `python /absolute/path/to/test.py`
2. Call with `-m pdb` so the debugger can load the code before hydra calls `chdir`
   `python -m pdb test.py`

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
pip install pdbpp
pip install hydra-core
```
```
import pdb
import hydra
from omegaconf import DictConfig


@hydra.main('config.yaml')      # config.yaml is an empty file
def main(cfg: DictConfig) -> None:
    pdb.set_trace()
    print(cfg.pretty())

    return


if __name__ == '__main__':
    main()
```

** Stack trace/error message **
```
$ python test.py
[5] > /home/bsl/code/tmp/outputs/2020-04-03/16-31-47/test.py(9)main()                                                                                         
(Pdb++) sticky                                                                                                                                                
> /home/bsl/code/tmp/outputs/2020-04-03/16-31-47/test.py(9)                                                                                                   

** Error in inspect.getsourcelines: source code not available **
(Pdb++)
```

## Expected Behavior

A window with source code showing for debugging.

## System information
- **Pdbpp version** : `0.10.2`
- **Hydra Version** :  `0.11.3`
- **Python version** : `3.7.6`
- **Virtual environment type and version** : `conda 4.7.12`
- **Operating system** : `Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`

**Comment by blueyed** [comment]
Thanks for the report.
Please try with pdbpp master, and report back.

**Comment by binshengliu** [comment]
Thanks. The issue does not exist on master f4f26d2.
