### ISSUE TITLE
pdbpp not responding to pdb commands

### ISSUE THREAD

**Issue by zachvalenta** [pdbpp/pdbpp#392]
* operating system: macOS Mojave 10.14.3
* shell: bash 3.2.57
* Python: 3.6.1
* dependency management: Poetry 1.0.5

__expected__

able to use pdb commands

__actual__

when I drop breakpoint and execute module, execution is stopped but debugger is not interactive

```sh
$ make test  # run tests

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[36] > /Users/zach/Desktop/zvmac/materials/sw/za/algos/algos/src/hacker_rank.py(9)ransom_note()
-> magazine_map = dict()
   5 frames hidden (try 'help hidden_frames')
n
ll
c
^D  # exit
```

**Comment by blueyed** [comment]
Looks like something might swallow/redirect stdin.

> PDB set_trace (IO-capturing turned off)

You are using pytest.
Try with `-s`, and without `make` (whatever that does after all).

I might look into it, but need steps to reproduce / investigate.

Also try pdbpp from Git master.

**Comment by zachvalenta** [comment]
Thanks for the help, `pytest` was indeed the culprit.

`make` refers to [GNU Make](https://www.gnu.org/software/make/); running the test suite via a `Makefile`

**Comment by blueyed** [comment]
Normally pytest should be handled fine though, and "IO-capturing turned off" indicates that it is doing something.
I know `make`.. :) - but I do not know your Makefile, i.e. if it redirects output etc.

**Comment by zachvalenta** [comment]
Yep, the issue was that I was not passing the `-s` flag. Thanks for the help!

**Comment by blueyed** [comment]
@zachvalenta that shouldn't be really necessary though - pytest handles it by itself ("IO-capturing turned off" - which you do not see with `-s`).
