### ISSUE TITLE
No module named 'readline'

### ISSUE THREAD

**Issue by noelevans** [pdbpp/pdbpp#401]
I'm trying to run tox with HEAD. It seems fine for py38, completing all of the tests sucessfully but for all the other versions, almost all the tests fail as below

```
tox --recreate -e py37
....
FAILED testing/test_pdb.py::test_stdout_reconfigured[False] - ModuleNotFoundError: No module named 'readline'
FAILED testing/test_pdb.py::test_set_trace_in_skipped_module - ModuleNotFoundError: No module named 'readline'
FAILED testing/test_pdb.py::test_interaction_no_exception - ModuleNotFoundError: No module named 'readline'
```

Is there another step I need to follow? FWIW I have readline installed for python 3.7, 3.6, 3.5 (and can use different pdbpp features fine with them). But with my limited understanding of tox it looks like it should get installed to the .tox venv. I'm using Ubuntu 20.04

**Comment by blueyed** [comment]
`tox -e py37` works for me.
Looks like an issue with your different Python version (installations), and/or tox itself.
I'm using pyenv to manage non-system Python versions (and link them into `~/bin` (added to `$PATH` of course)).
Closing for now, feel free to follow up though, of course.

**Comment by noelevans** [comment]
I'd been using asdf and then switched to pyenv on your suggestion. Through removing asdf I realised aliases in my bashrc were causing the problem.

Thank you very much for your help @blueyed
