### ISSUE TITLE
Publish package as a wheel

### ISSUE THREAD

**Issue by plannigan** [pdbpp/pdbpp#402]
Currently, only an sdist is [available to PyPi](https://pypi.org/project/pdbpp/0.10.2/#files). Based on the [CI config](https://github.com/pdbpp/pdbpp/blob/5904792eaf6a94cf277471ee02627014367e6c28/.travis.yml#L74), it looks like the intent is to also publish a wheel. Maybe there is an issue with that config.

Installing from an sdist does work, but requires `setuptoos-scm` to be installed even though it is not a runtime requirement.

**Comment by blueyed** [comment]
Fixed with the release of 0.10.3: https://pypi.org/project/pdbpp/0.10.3/#files
