### ISSUE TITLE
How do you hack the pdb path when working in pip's edit mode?

### ISSUE THREAD

**Issue by goodboy** [pdbpp/pdbpp#406]
Say I'm in a `virtualenv`, have clone the repo locally and installed with `pip install -e './path/to/pdbpp_repo'`. 

How the heck do I get it so the `pdb` module is overridden by the `pdppp` types?

**Comment by blueyed** [comment]
This requires creating a symlink in your virtualenv manually.
I've tried to work around this with a custom setuptools command, and might try again but IIRC it was not easy to ensure it gets uninstalled again.
(develop / editable mode is quite an incomplete hack in pip, and IIRC they do not want to add hacks on top - Ref: https://github.com/pypa/pip/pull/7795)

**Comment by blueyed** [comment]
I might not have understood the question - so to elaborate: the "pdb" module is created dynamically.
See https://github.com/pdbpp/pdbpp/blob/c15971f5ccf3f9465844daa8aecf4aeaf001b1b1/src/_pdbpp_path_hack/pdb.py.
