### ISSUE TITLE
You can't import pdbpp?

### ISSUE THREAD

**Issue by goodboy** [pdbpp/pdbpp#407]
I'm dreadfully confused at this point.

Is it expected that I **can't** `import pdbpp`?

As far as I can tell it seems the only way I can make this work is if I install in edit mode with `pip`?

This seems extremely wrong to me.

For example how am I supposed to use the derived `pdbpp.Pdb` (and other module routines) if I can't even import the package independent of plain old `pdb`?

**Comment by goodboy** [comment]
Ahh I understand now that you're overriding `pdb` with the `pdbpp` module but imo you should really still be able to import the package explicitly. This is super confusing imo.

**Comment by blueyed** [comment]
Fixed in f95703d96c708812a886dd397c26ab02d5a4a771.

**Comment by goodboy** [comment]
@blueyed thanks!
