### ISSUE TITLE
Using pdbpp as an API

### ISSUE THREAD

**Issue by sucrecacao** [pdbpp/pdbpp#409]
Hello,

I would like to use pdbpp as an API, to integrate it with my favorite editor kakoune.

I was wondering if there is a way to use it more or less like this:
```python
file_to_debug = pdbpp.load('foo.py')

# adding breakpoint to line 3 of foo.py
file_to_debug.add_breakpoint(3)

# being able to use command next, continue and step into 
file_to_debug.continue()     # should stop at the next breakpoint ( line 3 ) 

# being able to retrieve data from the right side panel 
file_to_debug.get_dir()    # return pdb 'dir()' command
```

**Comment by blueyed** [comment]
This is not possible nor planned.
The best currently is to drive it via stdin / sending keys (e.g. to a tmux pane etc).
