### ISSUE TITLE
Best practice for local variable named "sticky"

### ISSUE THREAD

**Issue by Shaunakde** [pdbpp/pdbpp#410]
I was trying to use `pdbpp` on a bit of code that has a local variable unfortunately named `sticky`. Once the debugger passes that line, the `sticky` command is replaced and now points to this variable. I was wondering what the best practice in a situation like this was (assuming I can't just rename the variable), and how would I recover the functionality of the `sticky` keyword? One solution would be to redundantly define `sticky_` as a keyword that functionally is similar to `sticky`. 

Would love to hear some thoughts / best practices. 

Minimum viable example:
```
def foo():
    bar = 10    # No issues here
    sticky = 100  # This overwrites the sticky command
```

**Comment by blueyed** [comment]
`!sticky` should work then.
Closing as answered, feel free to follow up.
