### ISSUE TITLE
Conda Package?

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#42]
Originally reported by: **Anthony Scopatz (Bitbucket: [scopatz](https://bitbucket.org/scopatz), GitHub: [scopatz](https://github.com/scopatz))**

----------------------------------------

Hi! Do you think you'll have a conda package at some point.  I'd like to play around with this. Thanks!

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/42

**Comment by antocuni** [comment]
*Original comment by* **florian.rathgeber (Bitbucket: [frathgeber](https://bitbucket.org/frathgeber), GitHub: Unknown)**:

----------------------------------------

@scopatz, I've started packaging the dependencies, but that'll take a while...

**Comment by antocuni** [comment]
*Original comment by* **Anthony Scopatz (Bitbucket: [scopatz](https://bitbucket.org/scopatz), GitHub: [scopatz](https://github.com/scopatz))**:

----------------------------------------

Cool, thanks!

**Comment by blueyed** [comment]
@antocuni 
Any update on this?

@scopatz
Is the package available by now?  (not using anaconda myself obviously)

**Comment by kynan** [comment]
@blueyed I packaged this back in 2017: https://anaconda.org/conda-forge/pdbpp
Recipe at https://github.com/conda-forge/pdbpp-feedstock

**Comment by blueyed** [comment]
@kynan 
Great.  I assume this issue can be closed then.

But you should update it (currently at 0.9.2).

**Comment by blueyed** [comment]
@kynan 
Please consider also creating a PR with an update for the README to contain information about this (if relevant, and you plan to maintain it).

**Comment by kynan** [comment]
Done, #137
