### ISSUE TITLE
How to start `pdb.set_trace` in "sticky" mode directly?

### ISSUE THREAD

**Issue by sucrecacao** [pdbpp/pdbpp#451]
Hello,

I debug my python by inserting `import pdb; pdb.set_trace()` in my code.

After that, I alway enter the `sticky` command for better understanding. 

Is there a way to directly start the `set_trace()` in sticky mode ?
Something like "pdb.set_trace(sticky=True)"

**Comment by jugmac00** [comment]
> Hello,
> 
> I debug my python by inserting `import pdb; pdb.set_trace()` in my code.
> 
> After that, I alway enter the `sticky` command for better understanding.
> 
> Is there a way to directly start the `set_trace()` in sticky mode ?

Yes!

Have a look at my PR for an updated documentation
https://github.com/pdbpp/pdbpp/pull/440/files

**Comment by sucrecacao** [comment]
I added 
```
pdb.DefaultConfig.sticky_by_default = True
```
At the top of my file and it worked perfectly

**Comment by jugmac00** [comment]
I am glad I could help!

**Comment by sucrecacao** [comment]
@jugmac00 
Do you know how to acheive the same behaviour when calling pdbpp from command line, like:
`python -m pdb file_to_debug.py` ?

**Comment by jugmac00** [comment]
Unfortunately, no.

```
❯ python -m pdb --help
usage: pdb.py [-c command] ... [-m module | pyfile] [arg] ...

Debug the Python program given by pyfile. Alternatively,
an executable module or package to debug can be specified using
the -m switch.

Initial commands are read from .pdbrc files in your home directory
and in the current directory, if they exist.  Commands supplied with
-c are executed after commands from .pdbrc files.

To let the script run until an exception occurs, use "-c continue".
To let the script run up to a given line X in the debugged file, use
"-c 'until X'".
```

Does not look like this is supported.

I also had a quick look at pdb's and pdb++'s source code :-/

What is your use case?

You can have both a user global and a repository specific config file.

**Comment by sucrecacao** [comment]
I think it would be nice to be able to use different config file, maybe with an environment variable, like
`PDB_CONFIG=.myconfigrc python -m pdb`

A workaround that can sometime work ( and work with sticky ) is to pass by the command line args:
`python -m pdb -c sticky myfile.py`

**Comment by jugmac00** [comment]
Well, you could create a feature request / new issue and see what @blueyed thinks about it, and if he'd accept a PR.
