### ISSUE TITLE
pip install does not override original pdb behavior

### ISSUE THREAD

**Issue by carand** [pdbpp/pdbpp#462]
After installing the package with pip the the original pdb will be loaded. If the pdb.py is called directly from the sources it works.

System Linux Mint 19.3

**Comment by carand** [comment]
Meybe it's better to rename the executalbe to pdbpp

**Comment by jugmac00** [comment]
`pdbpp` works as a drop-in replacement for `pdb`, so renaming it to `pdbpp` is not a thing.

You have given us very little details. For me it sounds like you are using two different Python environments.

If you want us to be able to help us, you need to be much more detailed. e.g. we need to know which `pip` you used and which Python interpreter.

**Comment by carand** [comment]
> `pdbpp` works as a drop-in replacement for `pdb`, so renaming it to `pdbpp` is not a thing.
> 
> You have given us very little details. For me it sounds like you are using two different Python environments.
> 
> If you want us to be able to help us, you need to be much more detailed. e.g. we need to know which `pip` you used and which Python interpreter.

I use python 2.7 and 3 6 as system defaults. Additionally python 3.7 and python 3.8 are installed. All pip versions should be >= 20 except for python 2.7.

I tried installation for python 3.6 and python 2.

**Comment by blueyed** [comment]
@carand 
Is this an editable install by chance?  (`pip install -e`)
In this case the hijacking does not work.
Otherwise it should look like this:
```
venv/bin/python -c 'import pdb; print(pdb)'                                                       🐍?
<module 'pdb' from '/tmp/venv/lib/python3.9/site-packages/_pdbpp_path_hack/pdb.py'>
```

Apart from that you can try using pdb++ from  Git master,  where it has been moved to `pdbpp` (and therefore  can be explicitly imported), and also the hijacking can be disabled using an env variable.

**Comment by carand** [comment]
@blueyed 
Maybe I'm doing something wrong.
 So let's do it by example:

after doing `pip3.6 install pdbpp` and `/usr/bin/python3.6 -c  'import pdb; print(pdb)'` I get this:
`<module 'pdb' from '/home/cmd/.local/lib/python3.6/site-packages/_pdbpp_path_hack/pdb.py'>`
Now calling pdb `pdb3.6 pdpp_test2.py` and I get the original behavior 
`> /home/cmd/repos/cpp/dev/pdpp_test2/pdpp_test2.py(1)<module>()`
`-> import pdb`
`(Pdb) `

I don't know what I'm doing wrong....
 The `pdpp_test.py` looks like this:

`import pdb`
`print("hello")`

**Comment by blueyed** [comment]
What does `which pdb3.6` give you?
Is this a wrapper around `python -m pdb`, possibly using another `python` then?
Check `import sys; sys.path` in there, and also the imported pdb module.

FWIW, this is how it should look like:
```
% venv/bin/python -m pdb t.py
[2] > /tmp/t.py(1)<module>()
-> print(42)
(Pdb++) q
% cat t.py
print(42)
```

**Comment by carand** [comment]
`which pdb3.6 `                                                                                                                                             
`/usr/bin/pdb3.6`
`which pdb3.6`
`/usr/bin/pdb3.6`
`ls -l /usr/bin/pdb3.6`
`/usr/bin/pdb3.6 -> ../lib/python3.6/pdb.py`
it's just a symlink made by the system. I thought it will be replaced by your library. So that I can call it.
if i run 
`python3.6 -m pdb pdpp_test2.py` it seems to work.

Maybe you should update your README, to make clear how to use this library. For me it was not clear that I need to use `python -m`

Anyhow, thanks for your help.

**Comment by jugmac00** [comment]
There is already a usage section in the readme, see https://github.com/pdbpp/pdbpp#usage

Also see https://docs.python.org/3/library/pdb.html for the official documentation of pdb, of which pdbpp is a drop-in replacement  - so it should work the same with some enhancements.

Usually you should not install a package into the system wide Python interpreter, but always use a virtual environment, see e.g. https://realpython.com/python-virtual-environments-a-primer/

Funny thing - even if you install pdbpp into a virtualenv and activate it, `which pdb` still resolves to `/usr/bin/pdb`.

So, my conclusion is - pdb was never meant to be a command line tool, but only used as a module, by setting a breakpoint in the source code or calling `python -m pdb`, but never as `pdb file` - maybe this binary is a special thing of your Linux distribution.

**Comment by carand** [comment]
> There is already a usage section in the readme, see https://github.com/pdbpp/pdbpp#usage
> 
> Also see https://docs.python.org/3/library/pdb.html for the official documentation of pdb, of which pdbpp is a drop-in replacement - so it should work the same with some enhancements.
> 

Firstly, the usage sections makes not clear that I need to use `python -m` and the pdp documentation will not solve the problem, that pdbpp can't be started by using `pdb <testfile>`.


> Usually you should not install a package into the system wide Python interpreter, but always use a virtual environment, see e.g. https://realpython.com/python-virtual-environments-a-primer/
> 


Your are right, if you say  i should not install packages system wide, but in this case it was much better for me to find out the issue.

> Funny thing - even if you install pdbpp into a virtualenv and activate it, `which pdb` still resolves to `/usr/bin/pdb`.
> 

I did not setup a virtualenv. 

> So, my conclusion is - pdb was never meant to be a command line tool, but only used as a module, by setting a breakpoint in the source code or calling `python -m pdb`, but never as `pdb file` - maybe this binary is a special thing of your Linux distribution.

I think pdb is  a command line tool on mac and linux.  pdb is marked as executable by default.
And I suppose that windows has a pdb.exe too.

Maybe I'm not experienced enough with python because I use the language only  simple tools.
But updating your usage section is not a bad idea.

**Comment by jugmac00** [comment]
@carand I checked back with a CPython core developer, and it is like I said:
`pdb` as a binary (from `/usr/bin/pdb`) is a Debian/Ubuntu specific shortcut.

So it is neither an official Python thing, nor a Linux thing, nor it has something to do with pdbpp.

I am sorry you experienced problems, but I think it is out of scope to update the readme for a distribution specific thing - although I am not a maintainer here, and it is not me to decide.

In future - please always use `python -m pdb` so always the correct Python interpreter is used - if you want to call pdb from the command line.

At least for me, it makes much more sense to set a breakpoint directly in the source code, ie via `breakpoint()` or via `import pdb;pdb.set_trace()`.

**Comment by carand** [comment]
It's okay. I always called pdb as command line tool. And set my breakpoints there. Thus 'python -m pdb' was new to me and I learned something new now. 

Thanks for help.
