### ISSUE TITLE
[question] clarify usage with ipython

### ISSUE THREAD

**Issue by apteryks** [pdbpp/pdbpp#470]
Hello,

I've read somewhere that pdbpp could be used with IPython; does that mean that launching pdbpp will work from inside an ipython session, or does it mean that the Pdb++ prompt will gain ipython support (features such as %timeit, %paste, etc)?  It seems the former, although I'd have liked the later.

pdbpp is great by itself, but one thing that is annoying for my flow is that it doesn't have a way (that I know) of understanding multi-line code fragments (this is accomplished using %paste in ipython).

Thanks for this great project!

**Comment by kkirsche** [comment]
I don't have a configuration for it handy, but I believe it involves using the `pdbrc.py` file to set aspects of the Pdb configuration to use `IPython.core.debugger.Pdb`

**Comment by apteryks** [comment]
OK, what I wanted in the end was having all the IPython support + ipdb's niceties such as `sticky`.  I could accomplish this by installing both `ipdb` and `pdbpp`, and setting my main debugger to `ipdb` via:

```sh
export PYTHONBREAKPOINT=ipdb.set_trace   # or ipdb.sset_trace
```
And put `breakpoint()` in the Python source to debug. Then, after ipdb starts, I can invoke pdbpp functions like `sticky` while being in the comfy IPython environment.
