### ISSUE TITLE
Python 3.4.3: Installable, but not importable

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#48]
Originally reported by: **jmagnusson (Bitbucket: [jmagnusson](https://bitbucket.org/jmagnusson), GitHub: [jmagnusson](https://github.com/jmagnusson))**

----------------------------------------

Using Python 3.4.3 (installed through `homebrew`) on my Mac 10.10 laptop I'm able to install `pdbpp` both within a virtualenv and in the system wide installation.

Running `pip freeze | grep pdbpp` shows the package, but look when I try to access some attributes that are specific to pdbpp on `pdb`:

```sh
$ python3 -c 'import pdb; print(pdb.pdb)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'pdb'
```
I.e. I can't find `pdbpp`.

I have no problems at all running the above command with Python 2.7.9 (also installed through `homebrew`):

```sh
$ python2 -c 'import pdb; print(pdb.pdb)'
<module 'pdb' (built-in)>
```

Note that I'm using `pdbpp==0.8.1` because `0.8.2` gives me the following:

```sh
python3 -c 'import pdb'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/_pdbpp_path_hack/pdb.py", line 3, in <module>
    execfile(os.path.join(
NameError: name 'execfile' is not defined
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/48

**Comment by antocuni** [comment]
*Original comment by* **Miroslav Shubernetskiy (Bitbucket: [miki725](https://bitbucket.org/miki725), GitHub: [miki725](https://github.com/miki725))**:

----------------------------------------

`execfile` was removed in Python3 which is what is causing the issue

**Comment by blueyed** [comment]
This appears to be fixed already.
