### ISSUE TITLE
Don't go into third party library on exception

### ISSUE THREAD

**Issue by cacharle** [pdbpp/pdbpp#487]
When an exception from a third party library is raised, I would like `pdb++` to stay in my code instead of going to the source of the exception in the library.

Current backtrace look like:

```
(Pdb++) bt
[0]   mymodule1.py(42)qux()
-> ...
[1]   mymodule2.py(42)baz()
-> ...
[2]   site-packages/thirdpartymodule1.py(42)foo()
-> ...
[3] > site-packages/thirdpartymodule2.py(42)bar()
-> ...
```

What I would like to see:

```
(Pdb++) bt
[0]   mymodule1.py(42)qux()
-> ...
[1]   mymodule2.py(42)baz()
-> ...
```

I guess this shouldn't be the default behavior, it would be nice if we could do that via configuration or some kind of hook.

Also, in my example, you only have to `up<Enter><Enter>` which is fine, but I generally have far more stack frame from third party in there so I have to press `<Enter>` 10 times and that's painful.

**Comment by blueyed** [comment]
See also https://github.com/pdbpp/pdbpp/issues/460.
Feel free to close as duplicate.

**Comment by cacharle** [comment]
Ah! sorry for the duplicate
