### ISSUE TITLE
REPL UX: `vi`-bindings not working anymore, dependency update issue?

### ISSUE THREAD

**Issue by goodboy** [pdbpp/pdbpp#494]
I pinned to the master branch a while back after reporting https://github.com/pdbpp/pdbpp/issues/480 and i swear everything was originally working great, but oddly now I can't seem to get reliable controls working again every time the repl enters?

I feel like i experienced this before and it was something to do with updating `pyrepl` and/or `fancycompleter`..

I noticed https://github.com/pdbpp/pdbpp/issues/260 which mentions both deps and am wondering if anyone else has noticed the same.

This is pretty frustrating for meeself since i prefer not to move my hands around the keyboard alot 😂

**Comment by blueyed** [comment]
What bindings do you mean (one example)?
Do you have colors with tab completions?
Do you get "[ not unique ]" after the first tab?
```
(Pdb++) import os
(Pdb++) os.
[ not unique ]
```

**Comment by goodboy** [comment]
Bleh, figured it out.

Env was pinned to `pyrepl=0.8.5.dev53+gca192a8` for some weird reason, not sure if this was due to installing from master at some point?

Anyway upgrading to `0.9.0` seems to put everything back as it should 😂 

Will test a bit if and if all good will close this.

**Comment by goodboy** [comment]
> Do you get "[ not unique ]" after the first tab?

@blueyed sorry just saw this. I *was* seeing all that prior but after just upgrading I'll have to test again - whole issue seems to have been the version of `pyrepl` afaict.

**Comment by goodboy** [comment]
@blueyed do i need to pin to a version >= `0.9.0` to avoid this issue again?

**Comment by goodboy** [comment]
Yeah gonna close this since that seems to have fixed everything for now, at least on recent master history.

Will re-open if issue resurfaces.

**Comment by blueyed** [comment]
Ok, still wondering what bindings you mean/use, which apparently are provided by pyrepl, but not readline then?!

**Comment by goodboy** [comment]
Nope, it's actually the opposite 😂 

If I uninstall `pyrepl` then the bindinds come back!

I'm re-opening this.

----
### `vi`-like kbindings summary:
- `alt-k` -> same as up arrow
- `alt-[` -> same as `esc` in terms of `vi` cancel mode

So these are more or less the real old school bindinds that i'm pretty sure are just the equivalent terminal combos from before they added those keys 😂 

I personally use them to avoid having to move my hands too much.

**Comment by goodboy** [comment]
Yeah, so now I see why i keep hitting this:

> By default, fancycompleter tries to use pyrepl if it finds it. To get colors you need a recent version, >= 0.8.2.

from https://github.com/pdbpp/fancycompleter#how-do-i-get-colors

Also is this bit out of date?

> If you are using Python 3, pyrepl does not work, and thus is not installed. Your only option to get colors is to use a patched readline, as explained below.

**Comment by goodboy** [comment]
@blueyed think i found where to add it in `pyrepl`:
https://github.com/pypy/pyrepl/blob/master/pyrepl/keymaps.py#L111

So more or less I'd like to see:
`alt-k` => switches to vi-mode and moves up one in history
`alt-l` => switches to vi normal mode

I think technically the combo `alt-]` is a terminal mapping for `esc` so this one might be good as well?

Not sure if I should make a separate issue on that repo or just send a patch and link here?
Suggestions welcome 😄

**Comment by blueyed** [comment]
> Also is this bit out of date?
> 
> > If you are using Python 3, pyrepl does not work, and thus is not installed. Your only option to get colors is to use a patched readline, as explained below.

Yes.

I think you should create a PR/patch for pyrepl.  (If I understood it correctly it lacks bindings that readline has.)
