### ISSUE TITLE
feat: import/export breakpoints from file

### ISSUE THREAD

**Issue by asdf8601** [pdbpp/pdbpp#497]
When I'm debugging complex programs I find my self adding many breakpoints and when I have to restart the debugger all breakpoints are gone. I thought that using a file could be very interesting to setup easily all breakpoints.

I've found a project that have implemented this: https://github.com/jasonprogrammer/pdbpp/blob/master/pdb.py#L455-L472

I would like to know what do you think about this and if it makes sense to add that functionality to pdbpp.

**Comment by blueyed** [comment]
You could add `break` commands to `~/.pdbrc` (also used by pdb), which is basically a list of commands to be executed on startup, or do something more fancy in `~/.pdbrc.py` (only for pdbpp).

Maybe just (un)commenting a block of commands based on the use case would be enough for the former already?  (For more complex code you would need to `exec(compile(…))` there, but could also import helpers from somewhere probably.)

**Comment by asdf8601** [comment]
Hi @blueyed, thank you for your quick response ;-) 

I have to say that I've tried `~/.pdbrc` and it works perfectly, the only problem I've found using it, it's that I would like to use a different file per project. So, it's possible define a ENVVAR which tells to pdb which file have to use (like `export PDBRC=/home/mgreco/prjA/pdbrc`) ? Or as you suggest could I write a function in `.pdbrc.py` which overrides the original function to implement something like that? I would like to try it.

**Comment by asdf8601** [comment]
Hey, I just dropped by to say that I made it work. This is what I've added to my `.pdbrc.py`:

```python
def read_pdbrc():
    pdb_bp = os.getenv("PDBrc")
    if pdb_bp is None:
        return
    with open(pdb_bp, 'r') as f:
        exec(f.read())


read_pdbrc()

```

Thank you so much for tips on this @blueyed :love_you_gesture:

**Comment by jamilraichouni** [comment]
> Hi @blueyed, thank you for your quick response ;-) 
> 
> 
> 
> I have to say that I've tried `~/.pdbrc` and it works perfectly, the only problem I've found using it, it's that I would like to use a different file per project. So, it's possible define a ENVVAR which tells to pdb which file have to use (like `export PDBRC=/home/mgreco/prjA/pdbrc`) ? Or as you suggest could I write a function in `.pdbrc.py` which overrides the original function to implement something like that? I would like to try it. 

The file .pdbrc can be given multiple times. One in your home directory to setup stuff that is common to all projects (e. g. aliases you always want to use) and a file in the project directory where you start your debugging session.

**Comment by asdf8601** [comment]
Oh, lovely. That explains the strange behavior when I start using the .pdbrc file name in my script. I can remove that code and use it as is. Thank you!
