### ISSUE TITLE
Getting AttributeError when running doctests with nose 1.3.0

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#50]
Originally reported by: **Luke Lee (Bitbucket: [perkolasoft](https://bitbucket.org/perkolasoft), GitHub: [perkolasoft](https://github.com/perkolasoft))**

----------------------------------------

Here's a traceback of the error I'm seeing when trying to run doctests with nose using the `--doctest-tests` and `--with-doctest` flags:

```
#!python

======================================================================
ERROR: nose.plugins.doctests:DocTestCase.runTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/doctest.py", line 2196, in runTest
    test, out=new.write, clear_globs=False)
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/doctest.py", line 1415, in run
    self.debugger = _OutputRedirectingPdb(save_stdout)
  File "/Users/durden/.virtualenvs/dmvc/lib/python2.7/site-packages/nose/plugins/doctests.py", line 92, in __init__
    _orp.__init__(self, out)
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/doctest.py", line 338, in __init__
    pdb.Pdb.__init__(self, stdout=out)
  File "/Users/durden/.virtualenvs/dmvc/lib/python2.7/site-packages/pdb.py", line 215, in __init__
    self.stdout = self.ensure_file_can_write_unicode(self.stdout)
  File "/Users/durden/.virtualenvs/dmvc/lib/python2.7/site-packages/pdb.py", line 219, in ensure_file_can_write_unicode
    if not hasattr(f, 'stream') and f.encoding and f.encoding.lower() != 'utf-8':
AttributeError: StringIO instance has no attribute 'encoding'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/50

**Comment by antocuni** [comment]
*Original comment by* **Luke Lee (Bitbucket: [perkolasoft](https://bitbucket.org/perkolasoft), GitHub: [perkolasoft](https://github.com/perkolasoft))**:

----------------------------------------

I've tracked the problem line down to this commit:

https://bitbucket.org/antocuni/pdb/commits/4bda65ac8f8cc9b1850e0301669aac39200f2f9a

I changed the line in question to the following and everything works.  However, not sure if this is a 'real' fix.  I can submit a PR if the following seems reasonable:

https://bitbucket.org/perkolasoft/pdb/commits/6ce06ce6dbdb2aa89b0146ff2c71c27970d0945e

**Comment by antocuni** [comment]
*Original comment by* **Nikolaos-Digenis Karagiannis (Bitbucket: [Digenis](https://bitbucket.org/Digenis), GitHub: [Digenis](https://github.com/Digenis))**:

----------------------------------------

Duplicates PR 40 https://bitbucket.org/antocuni/pdb/pull-request/40/fix-ensure_file_can_write_unicode/diff  
Unfortunately the developers haven't expressed interest.

**Comment by blueyed** [comment]
This has been fixed already (via https://bitbucket.org/antocuni/pdb/pull-requests/40/fix-ensure_file_can_write_unicode).
