### ISSUE TITLE
Is there a way to revert back to standard PDB, perhaps via an env var?

### ISSUE THREAD

**Issue by dougthor42** [pdbpp/pdbpp#505]
Is there a way to revert back to standard PDB when running a program, perhaps via an env var?

### Use Case:

I am seeing a strange error with Qt that I think *may* be related to pdb++. I'd like to run my program using the standard debugger instead to see if the error still occurs, but I don't want to `pip uninstall pdbpp` just for this check.

Granted, uninstalling and reinstalling pdbpp is not _that_ hard to do...

### Example:

```console
$ PDBPP_DISABLED=true python my_code.py
```

### Expected Result:

Program drops into the built-in `pdb` when a breakpoint is hit, instead of `pdb++`.

### Workaround

```console
$ pip uninstall pdbpp -y
$ python my_code.py
$ pip install pdbpp
```

**Comment by dougthor42** [comment]
(For the record, the issue I'm seeing still happens with regular `pdb`, so I don't think there's anything wrong with `pdb++`)

**Comment by blueyed** [comment]
To answer the question: `PDBPP_HIJACK_PDB=0` can be used, mentioned in the docs.

**Comment by dougthor42** [comment]
Thanks! That's exactly what I was looking for.

For those who might be trying to find the docs that mention it, check out the docstring for `pdb.py`:

https://github.com/pdbpp/pdbpp/blob/b62a3381bd1db8fa3ffaa46579f477b187e2f37c/src/_pdbpp_path_hack/pdb.py#L5

**Comment by blueyed** [comment]
Oh, thanks for pointing that out..

when grepping I found it in a local build dir, left over from https://github.com/pdbpp/pdbpp/pull/378 (https://github.com/blueyed/pdbpp/tree/readme), and assumed it was in the readme already.
