### ISSUE TITLE
Syntax highlighting gets broken

### ISSUE THREAD

**Issue by delfick** [pdbpp/pdbpp#507]
Hello,

It seems that sometimes the syntax highlighting doesn't work and it colors code as if it's a doc comment if it includes the end `"""` of a method docstring at the top of the snippet currently shown.
<img width="470" alt="Screen Shot 2022-10-19 at 10 57 39 am" src="https://user-images.githubusercontent.com/109301/196566547-af0e29d8-9947-4fc1-b1c8-b9eb66a01043.png">

Is there a way to make it not do syntax highlighting? or better, Is there a way for it to realise that `"""` is the end of a multiline string?

**Comment by blueyed** [comment]
I am not sure, but this might be fixed in master already, where it would highlight the complete file (internally/cached), and not just the excerpts.

**Comment by delfick** [comment]
I just tried version from git and that does seem to be the case :)
