### ISSUE TITLE
Pdb++ should work around the list invocation issue

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#51]
Originally reported by: **Michał Pawłowski (Bitbucket: [bmsss](https://bitbucket.org/bmsss), GitHub: [bmsss](https://github.com/bmsss))**

----------------------------------------

In Pdb++ local variables and their declarations take precedence over debugger commands.

For example `(Pdb++) c = 1` will not toggle `continue`. Same with `(Pdb++) c`, when there is a `c` local variable defined.

However, another pitfall is not resolved - `list(xrange(10))` will print `*** Error in argument: u'(xrange(10))'`. To work around this the user has to do: `print list(xrange(10))` (or `p` instead of `print`).

Making the globals take precedence over debugger commands is a no-go. 

The only simple fix I can think of is to print something like:
```
*** Error in argument: u'(xrange(10))'. The command was interpreted as an invocation of the debugger `list` command. Prefix the command with `print` to interpret is as Python code. 
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/51

**Comment by blueyed** [comment]
Addressed by https://github.com/antocuni/pdb/pull/85, and duplicate of #69.
