### ISSUE TITLE
`next` command is clashing with the Python "next" builtin method

### ISSUE THREAD

**Issue by amatmv** [pdbpp/pdbpp#510]
I cannot execute the Python `builtins.next` method to go through an iterator because the "next" command is bound to Pdb

**Comment by jugmac00** [comment]
use
```
!next
```

Also see https://docs.python.org/3/library/pdb.html#pdbcommand-0

**Comment by amatmv** [comment]
Nice! Thank you @jugmac00

**Comment by blueyed** [comment]
@amatmv where you using `next(it)`?  That should at least work on master.  (see also https://github.com/pdbpp/pdbpp/pull/477)
