### ISSUE TITLE
Tab autocompletion doesn't work on OSX

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#55]
Originally reported by: **Mikko Ohtamaa (Bitbucket: [miohtama](https://bitbucket.org/miohtama), GitHub: [miohtama](https://github.com/miohtama))**

----------------------------------------

Python 3.4 from Homebrew

OSX Yosemite

Tested with two different terminals.

Pdb++ inserts a tab character instead of doing autocompletion.

Not sure where I should start poking to see what's wrong.

![Screen Shot 2016-01-30 at 23.20.03.png](https://bitbucket.org/repo/Grbzr/images/3390211469-Screen%20Shot%202016-01-30%20at%2023.20.03.png)

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/55

**Comment by theY4Kman** [comment]
See also #74 and [this comment](https://github.com/antocuni/pdb/issues/74#issuecomment-346999806) for a workaround.

**Comment by blueyed** [comment]
Closing as duplicate of #74.
