### ISSUE TITLE
ordereddict installation

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#56]
Originally reported by: **Anonymous**

----------------------------------------

ordereddict is a requirement/installs for newer versions of Python. It looks like it is only being used in one place. Since most major packages are dropping Python 2.6 <, would you be ok with a pull request to deprecate this?

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/56

**Comment by hugovk** [comment]
Python 2.6 has been dropped in https://github.com/antocuni/pdb/commit/c7c51504e2e59a7abce3fbbee19bfdb6bb9727c7#diff-354f30a63fb0907d4ad57269548329e3. Can this issue be closed?

**Comment by antocuni** [comment]
yes, good idea. I removed all the leftovers of 2.6 support in 928b5b3
