### ISSUE TITLE
autocomplete for get attrs doesnt work on anaconda python 3.5 distribution

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#59]
Originally reported by: **Derrick Chambers (Bitbucket: [d-chambers](https://bitbucket.org/d-chambers), GitHub: [d-chambers](https://github.com/d-chambers))**

----------------------------------------

I just installed anaconda (python 3.5) on a new system. After pip installing pdbpp the auto-complete for getattr after hitting the tab key doesn't work.

For  example
```python
(Pdb++) import request
(Pdb++) r<tab> --- this works by suggesting request
```
however,
```python
(Pdb++)request.<tab> ---- this fails to auto-complete any of the request library attributes. 
```
Anyone else have this issue? 

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/59

**Comment by blueyed** [comment]
Is this still an issue?
