### ISSUE TITLE
Terminal256 not enabled on xterm

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#65]
Originally reported by: **Jiri Bajer (Bitbucket: [sarimak](https://bitbucket.org/sarimak), GitHub: [sarimak](https://github.com/sarimak))**

----------------------------------------

Support for terminal introduced in issue #30 tests for "color256" in TERM but not for "xterm" - even if enabled in config. See https://bitbucket.org/antocuni/pdb/src/cf937bbd910a8f7fe2b84af7cf5ee9dc96c2fe25/pdb.py?at=default#pdb.py-352

Hacky workaround:

class Config(pdb.DefaultConfig):
    use_terminal256formatter = True

    def setup(self, pdb):
        pdb_class = pdb.__class__
        pdb_class._lexer = PythonLexer()
        pdb_class._fmt = Terminal256Formatter(style="your Pygments favourite style")

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/65

**Comment by blueyed** [comment]
Should be fixed since deb3a62.
