### ISSUE TITLE
pdbpp overrides python keywords and/or basic functions

### ISSUE THREAD

**Issue by brianbruggeman** [pdbpp/pdbpp#69]
At no point should `pdbpp` override any [python keyword](https://docs.python.org/3/reference/lexical_analysis.html#keywords) or [default function](https://docs.python.org/3.6/library/functions.html).  

Example of one problem:

`pdbpp` overrides `list`, which is a default function available within every module.

This causes something like the following to fail:

    (Pdb++) x = 'abc'
    (Pdb++) list(x)
    *** Error in argument: 'x'

This problem is much more pronounced in python 3 where most functions now return an iterator.

**Comment by blueyed** [comment]
JFI: you can use `!list(x)` in this case.

**Comment by antocuni** [comment]
note also that this behavior is **not** peculiar to pdb++, but it is inherited from the standard pdb:
```
(Pdb) x = 'abc'
(Pdb) list(x)
*** Error in argument: '(x)'
```

I agree that it would be nice if pdb++ were smart enough to automatically detect whether `list` is used as a command or as a function call. I'd be glad to merge a PR about it 😊

**Comment by blueyed** [comment]
This gets addressed/fixed by #82 - ready to be merged, but would rather have somebody ACK it.

**Comment by blueyed** [comment]
With IPython it might prevent you from `exit`ing or `quit`ting (https://github.com/antocuni/pdb/issues/76).
