### ISSUE TITLE
pdb command to call pdb.disable

### ISSUE THREAD

**Issue by blueyed** [pdbpp/pdbpp#75]
`import pdb; pdb.disable()` is such a nice feature that it should have a command.

`disable` is already taken for breakpoints.

Something short like `cc[ont]` would be nice.

**Comment by antocuni** [comment]
First, I'd like to make sure that I understood your use case: you have a program which contains a bunch of `pdb.set_trace()`; at some point, you would like to type ``ccont`` to continue the execution **without** breaking at the subsequent `set_trace()`s. Is this correct?

I am fine to add a new command, but only if it's not obscure. E.g., I don't understand what ``ccont`` stays for :).

Moreover, note that you can easily add custom commands using `pdbrc.py`; e.g., see [this example](https://github.com/antocuni/pdb/blob/master/pdbrc.py#L37)

**Comment by blueyed** [comment]
Yes, you understood it correctly.
It might be just a single `set_trace`, which gets hit by lots of tests then though.

`ccont` came up via `cont(inue)`, which is taken already.
I agree that the name is obscure.

**Comment by blueyed** [comment]
`import pdb; pdb.disable()` is good enough for me for now.
