### ISSUE TITLE
Could you please fix test_pdb.py ?

### ISSUE THREAD

**Issue by callmekohei** [pdbpp/pdbpp#80]
I think that test_pdb.py to needs a little bit of modifications.

`test_pdb.py` has short of `hidden frames`.

I'm glad of you to modify test_pdb.py directly.

Thank you.

https://github.com/antocuni/pdb/pull/78

**Comment by blueyed** [comment]
Done by now, thanks for the PR!

**Comment by callmekohei** [comment]
Hi! Thank you!  :-)
