### ISSUE TITLE
pdb++ failing on import readline Win10/Anaconda3 for pytest dropin

### ISSUE THREAD

**Issue by obeavers** [pdbpp/pdbpp#81]
Not sure what changed as this was working fine, but now when I call py.test --pdb tests, I get:

```
 File "C:\Users\olive\Anaconda3\lib\site-packages\fancycompleter.py", line 220, in __init__
    self.config.setup()
  File "C:\Users\olive\Anaconda3\lib\site-packages\fancycompleter.py", line 173, in setup
    self.readline, supports_color = self.find_best_readline()
  File "C:\Users\olive\Anaconda3\lib\site-packages\fancycompleter.py", line 169, in find_best_readline
    import readline
ModuleNotFoundError: No module named 'readline'


```

How can this get resolved?

**Comment by blueyed** [comment]
Does `import readline` work for you?
I've seen cases where this fails due to a broken Python installation already.

Otherwise it might also be related to https://github.com/antocuni/pdb/pull/85, but think it is rather not.

**Comment by antocuni** [comment]
pdb++ depends on fancycompleter, and the latter requires `pyreadline` on windows:
https://bitbucket.org/antocuni/fancycompleter/src/22e3669eeeb48134ea6df1114ec7d70415d4cafc/setup.py?at=default&fileviewer=file-view-default#setup.py-10

So, it looks like a broken installation to me
