### ISSUE TITLE
[Hint] How to use pdbpp as ipdb replacement with pytest?

### ISSUE THREAD

**Issue by fkromer** [pdbpp/pdbpp#92]
There is [`pytest-ipdb`](https://github.com/mverteuil/pytest-ipdb) to allow interactive debugging in `pytest` with `ipdb`. However it is not maintained (aka "supported") any more:

> I am no longer supporting this tool. Please see pdb++ as a far more capable alternative that doesn't require plugins or special imports.
>
>pdb++: https://pypi.python.org/pypi/pdbpp/
> 
> Provides ipdb on failures for py.test.

How can I use `pdbpp` for interactive debugging in `pytest`?

**Comment by blueyed** [comment]
> Provides ipdb on failures for py.test.

I am not sure if this is correct (comes from https://github.com/mverteuil/pytest-ipdb).
/cc @mverteuil

> How can I use pdbpp for interactive debugging in pytest?

Just use `pytest --pdb` to trigger pdb (and pdbpp when installed) on failures, or use the usual `__import__('pdb').set_trace()` to trigger it manually.

Please make sure to install pdbpp non-editable (i.e. do not use `pip install -e` when installing it from a source checkout).

I'm not sure why you are opening this issue here after https://github.com/pytest-dev/pytest/issues/3412#issuecomment-382801502 though.

**Comment by fkromer** [comment]
> I'm not sure why you are opening this issue here after pytest-dev/pytest#3412 (comment) though.

`pytest --pdb` enters `Pdb++` in "interactive" mode just fine. Feels just bit different... sorry. (Cross referencing w.r.t. to tool integrations is kind of helpful for future reference.)

**Comment by floer32** [comment]
For posterity/ search wanderers - this is the bit of `pdb` config (which works with `pdbpp`) to add an option for dropping into IPython easily. (You could do the import/embed directly too, but I like having an alias...)

```
# Add to a .pdbrc in your $PWD or $HOME
# See also: docs.python.org/3/library/pdb.html#pdbcommand-alias
alias ipy from IPython import embed; embed()
```

**Comment by blueyed** [comment]
@hangtwenty 
You can also use `--pdbcls ipdb:__main__.debugger_cls` with pytest (via https://github.com/pytest-dev/pytest/issues/2064#issuecomment-492705928).

I wonder if we could/should have a command similar to the existing `interact`, which would use IPython then.  Ref: https://github.com/antocuni/pdb/blob/3afb7285c94554d8546e434aecc1a9bb6c6bade5/pdb.py#L930-L939

**Comment by mverteuil** [comment]
Ah, sorry. I didn't mean that it was a code complete replacement, more that I saw absolutely no need for my project anymore once pdbpp came along and solved the problem better than I had. There were some edge cases with some environments for my project that I have not seen with pdbpp, and therefore I suggest it as the replacement.

Just posting for posterity.

**Comment by blueyed** [comment]
btw: with https://github.com/pdbpp/pdbpp/pull/349 you would get "ipdb++>" also in the prompt to indicate the pdbpp is used additionally / inside of / with ipdb.  Not too convinced about this myself, but the idea was to indicate directly that it is hijacking pdb, which ipdb then uses.  What do you think? Comments/feedback appreciated over there.
