### ISSUE TITLE
Make `edit at line` command work for sublime text

### ISSUE THREAD

**Issue by antoine-gallix** [pdbpp/pdbpp#94]
Currently, the `edit` command runs the following command:

    $EDITOR +line file

As this notation might be a standard for some editors, this doesn't work for sublime text, where the syntax for opening a file is:

    subl file:line

I propose an option that would change the default editor call syntax to the colon-notation. Like:

```
editor_line_syntax = 'option' # default, give the line as a command option.  $EDITOR +<line> <file>
                     'suffix'  # (give the file line as a suffix, as accepted by sublime text : $EDITOR <file>:<line>
```

**Comment by antoine-gallix** [comment]
As a workaround this problem for fish users, create a script that does the conversion:
```shell
#!/usr/bin/env fish
set line_arg $argv[1]
set file $argv[2]
set line (echo $line_arg | string match -r '\d+')
exec subl "$file:$line"
```
And then in `~/.pdbrc`

```python
import pdb
class Config(pdb.DefaultConfig):
    editor = '/path/to/your/script/open_to_fileline_subl_adapter.fish'
```

This does the job

**Comment by blueyed** [comment]
I will add a new `edit_cmd` setting, where `{lineno}` and `{filename}` get replaced in every item (it should be a list of args, but a single command could be supported also).

E.g. `edit_cmd = ["subl", "{filename}:{lineno}"]`.

Does that sound good?

**Comment by blueyed** [comment]
Well, actually the `editor` setting could be kept, but we would try to format `{lineno}`/`{filename}`, or `%d`/`%s` in there.

I think optionally handling a list is also nice.

**Comment by blueyed** [comment]
WIP: https://github.com/antocuni/pdb/pull/165

**Comment by antoine-gallix** [comment]
looks good!

**Comment by blueyed** [comment]
Have you tried it yet?
Need to review/revisit it myself - it was done quite ad-hoc.

**Comment by blueyed** [comment]
Does `subl 'with space':12` work?
Or should it rather be `subl 'with space:12'`?

**Comment by blueyed** [comment]
@antoine-gallix 
gentle ping

**Comment by antoine-gallix** [comment]
Sorry I was away for a very long time. I´ll try that

**Comment by antoine-gallix** [comment]
> Does subl 'with space':12 work?
> Or should it rather be subl 'with space:12'?

both work

**Comment by antoine-gallix** [comment]
`editor = "subl {filename}:{lineno}"` in `.pdbrc.py` is working well!

**Comment by antoine-gallix** [comment]
PR for documentation there: https://github.com/antocuni/pdb/pull/227

**Comment by antoine-gallix** [comment]
and here is doc update for the config https://github.com/antocuni/pdb/pull/227
